name: Build Windows Executable

on:
    workflow_dispatch:
    push:
      tags:
        - 'v*'
jobs:
    build-windows:
      runs-on: windows-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          pip install requests
          pip install pandas
          pip install openpyxl
          pip install psutil

      - name: Build executable
        run: python build_windows.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: MatelasProcessor-Windows
          path: dist/
